name: api_core
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - expat=2.7.1
  - libffi=3.4.4
  - openssl=3.0.17
  - pip=25.1
  - python=3.12.11
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.15
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - annotated-types==0.7.0
      - anyio==4.10.0
      - brotli==1.1.0
      - cffi==1.17.1
      - charset-normalizer==3.4.3
      - click==8.2.1
      - colorama==0.4.6
      - cssselect2==0.8.0
      - dnspython==2.7.0
      - email-validator==2.2.0
      - fastapi==0.116.1
      - fonttools==4.59.1
      - greenlet==3.2.4
      - h11==0.16.0
      - idna==3.10
      - jinja2==3.1.6
      - markupsafe==3.0.2
      - pillow==11.3.0
      - psycopg2-binary==2.9.10
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydyf==0.11.0
      - pyjwt==2.10.1
      - pyphen==0.17.2
      - python-multipart==0.0.20
      - pytz==2025.2
      - reportlab==4.4.3
      - sniffio==1.3.1
      - sqlalchemy==2.0.43
      - starlette==0.47.2
      - tinycss2==1.4.0
      - tinyhtml5==2.0.0
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - uvicorn==0.35.0
      - weasyprint==66.0
      - webencodings==0.5.1
      - zopfli==0.2.3.post1
